import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Heart, Menu, Search, ShoppingBag, Sparkles, User } from "lucide-react";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 w-full border-b border-rose-100 bg-white/80 backdrop-blur-md supports-[backdrop-filter]:bg-white/80">
          <div className="container flex h-20 items-center justify-between px-4 md:px-8">
            <div className="flex items-center space-x-4">
              <Link href="/" className="flex items-center space-x-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-rose-400 to-pink-500">
                  <Sparkles className="h-5 w-5 text-white" />
                </div>
                <span className="font-bold text-2xl bg-gradient-to-r from-rose-600 to-pink-600 bg-clip-text text-transparent">
                  Modest Muse
                </span>
              </Link>
            </div>

            <nav className="hidden md:flex items-center space-x-8">
              <Link
                href="/hijabs"
                className="text-sm font-medium text-gray-700 hover:text-rose-600 transition-colors relative group"
              >
                Hijabs
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-rose-600 transition-all group-hover:w-full"></span>
              </Link>
              <Link
                href="#"
                className="text-sm font-medium text-gray-700 hover:text-rose-600 transition-colors relative group"
              >
                Dupattas
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-rose-600 transition-all group-hover:w-full"></span>
              </Link>
              <Link
                href="#"
                className="text-sm font-medium text-gray-700 hover:text-rose-600 transition-colors relative group"
              >
                Abayas
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-rose-600 transition-all group-hover:w-full"></span>
              </Link>
              <Link
                href="#"
                className="text-sm font-medium text-gray-700 hover:text-rose-600 transition-colors relative group"
              >
                Accessories
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-rose-600 transition-all group-hover:w-full"></span>
              </Link>
              {/* <Link
                href="#"
                className="text-sm font-medium text-rose-600 hover:text-rose-700 transition-colors relative group"
              >
                Sale
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-rose-600 transition-all group-hover:w-full"></span>
              </Link> */}
            </nav>

            <div className="flex items-center space-x-3">
              <Button variant="ghost" size="icon" className="hidden md:flex hover:bg-rose-50 hover:text-rose-600">
                <Search className="h-5 w-5" />
              </Button>
              <Button variant="ghost" size="icon" className="hover:bg-rose-50 hover:text-rose-600 relative">
                <Heart className="h-5 w-5" />
              </Button>
              <Button variant="ghost" size="icon" className="hover:bg-rose-50 hover:text-rose-600">
                <User className="h-5 w-5" />
              </Button>
              <Button variant="ghost" size="icon" className="hover:bg-rose-50 hover:text-rose-600 relative">
                <ShoppingBag className="h-5 w-5" />
                <span className="absolute -top-1 -right-1 h-4 w-4 bg-rose-500 text-white text-xs rounded-full flex items-center justify-center">
                  2
                </span>
              </Button>
              <Button variant="ghost" size="icon" className="md:hidden">
                <Menu className="h-5 w-5" />
              </Button>
            </div>
          </div>
        </header>
        <main>{children}</main>
        <footer className="w-full py-8 bg-gray-900 text-gray-300">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-center space-x-3">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-rose-400 to-pink-500">
                <Sparkles className="h-4 w-4 text-white" />
              </div>
              <span className="font-bold text-xl text-white">Modest Muse</span>
            </div>
            <p className="text-sm text-gray-400">© 2025 Modest Muse. All rights reserved.</p>
            <nav className="flex gap-6">
              <Link href="#" className="text-sm hover:text-white transition-colors">
                Terms of Service
              </Link>
              <Link href="#" className="text-sm hover:text-white transition-colors">
                Privacy Policy
              </Link>
              <Link href="#" className="text-sm hover:text-white transition-colors">
                Contact Us
              </Link>
            </nav>
          </div>
        </div>
      </footer>
      </body>
    </html>
  );
}
